######################################################################
# Automatically generated by qmake (2.01a) Tue May 6 14:35:48 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src
QT += xml

# Input
HEADERS += src/geofoto.h src/gpsarray
SOURCES += src/geofoto.cpp src/main.cpp
